"""
This type stub file was generated by pyright.
"""

def murmur3_32(data, seed=...): # -> int:
    """MurmurHash3 was written by Austin Appleby, and is placed in the
    public domain. The author hereby disclaims copyright to this source
    code."""
    ...

