"""
This type stub file was generated by pyright.
"""

class RendezvousHash:
    """
    Implements the Highest Random Weight (HRW) hashing algorithm most
    commonly referred to as rendezvous hashing.

    Originally developed as part of python-clandestined.

    Copyright (c) 2014 Ernest W. Durbin III
    """
    def __init__(self, nodes=..., seed=..., hash_function=...) -> None:
        """
        Constructor.
        """
        ...
    
    def add_node(self, node): # -> None:
        ...
    
    def remove_node(self, node): # -> None:
        ...
    
    def get_node(self, key): # -> str | None:
        ...
    


