"""
This type stub file was generated by pyright.
"""

from pymemcache.client.base import Client, PooledClient
from pymemcache.client.hash import HashClient
from pymemcache.client.retrying import RetryingClient
from pymemcache.exceptions import MemcacheClientError, MemcacheError, MemcacheIllegalInputError, MemcacheServerError, MemcacheUnexpectedCloseError, MemcacheUnknownCommandError, MemcacheUnknownError

